app = "druth-or-tare"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[processes]
app = "bun run index.js"

[http_service]
  internal_port = 3000
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[machines]
  [machines.app]
    count = 1
    vm_size = "shared-cpu-1x"
    memory = 1024
